//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Khareedo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderDetail
    {
        public int orderId { get; set; }
        public int payment_type { get; set; }
        public int total_amount { get; set; }
        public Nullable<int> total_discount { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<int> total_items { get; set; }
    
        public virtual PaymentType PaymentType { get; set; }
        public virtual Order Order { get; set; }
    }
}
